project_id = "dmmmwrqtbwtmqtvoxdxc"

[functions.create-client-user]
verify_jwt = true

[functions.update-client-user]
verify_jwt = true

[functions.create-employee-user]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true
